feat(stylelint): add declaration-property-max-values and selector-not-notation rules
zendeskgarden/stylelint-config pull request #237
Opened 2022-04-22 16:01 UTC by Francois-Esquire

…-notation rules

- [ ] **BREAKING CHANGE?** 

## Description

Adding new rule definitions added since `v14.5.3` - `v14.7.1`.

## Detail

Adding [`declaration-property-max-values`](https://github.com/stylelint/stylelint/blob/main/lib/rules/declaration-property-max-values/README.md) & [`selector-not-notation`](https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-not-notation/README.md) to the rules.

2022-04-22 16:31 UTC, jzempel requested changes
PR is missing the "peerDependencies" update. Please compare with https://github.com/zendeskgarden/stylelint-config/pull/221 and update the PR title with BREAKING CHANGE `!` notation.

2022-04-25 23:38 UTC, mtomcal commented
Will merge with the following commit title:

```feat(stylelint)!: add declaration-property-max-values and selector-not-notation rules```

and following commit message:

```
BREAKING CHANGE: add declaration-property-max-values and selector-not-notation rules

- Add `declaration-property-max-values`
- Add `selector-not-notation`
```

2022-04-26 12:59 UTC, jzempel requested changes

2022-04-26 12:59 UTC, jzempel commented on package.json
> +    "stylelint": "^14.7.1",
This peer should be the minimum version that added the new rules. So `^14.7.0`.

2022-04-26 18:39 UTC, jzempel approved these changes

2022-04-26 18:45 UTC, merged